version: '3'
services:
  vectr:
    image: ${VECTR_IMAGE}
    ports:
      - "${VECTR_EXTERNAL_PORT}:8081"
    volumes:
      - ${VECTR_SSL_CERTS_VOLUME}:/certs:ro
    environment:
      - VECTR_HOSTNAME=${VECTR_HOSTNAME}
      - VECTR_PORT=${VECTR_PORT}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - VECTR_DATA_KEY=${VECTR_DATA_KEY}
      - JWS_KEY=${JWS_KEY}
      - JWE_KEY=${JWE_KEY}
      - VECTR_EXTERNAL_HOSTNAME=${VECTR_EXTERNAL_HOSTNAME}
      - VECTR_EXTERNAL_PORT=${VECTR_EXTERNAL_PORT}
      - CA_PASS=${CA_PASS}
      - VECTR_FEATURES_SSLCONF=${VECTR_FEATURES_SSLCONF}
      - VECTR_SSL_CRT=${VECTR_SSL_CRT}
      - VECTR_SSL_KEY=${VECTR_SSL_KEY}
      - RESET_SSL=${RESET_SSL}
      - RATE_LIMIT_MAX_REQUESTS=${RATE_LIMIT_MAX_REQUESTS}
volumes:
  ${VECTR_SSL_CERTS_VOLUME}:
    external: true
